const styles = {
  wrapper: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: '100vh',
    padding: '20px',
    transition: 'background-color 0.3s ease-in-out',
  },
  appContainer: {
    display: 'flex',
    width: '95%',
    maxWidth: '1200px',
    height: '85vh',
    borderRadius: '12px',
    overflow: 'hidden',
    boxShadow: '0 5px 15px rgba(0, 0, 0, 0.1)',
    transition: 'background-color 0.3s ease-in-out, box-shadow 0.3s ease-in-out',
  },
  sidebar: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    transition: 'all 0.3s ease-in-out, background-color 0.3s ease-in-out, border-right 0.3s ease-in-out',
    overflow: 'hidden',
  },
  sidebarHeader: {
    padding: '15px',
    borderBottom: '1px solid #ddd',
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    transition: 'border-bottom 0.3s ease-in-out',
  },
  sidebarTitle: {
    margin: 0,
    fontSize: '1.2rem',
    fontWeight: '600',
    transition: 'color 0.3s ease-in-out',
  },
  newChatButton: {
    padding: '8px 12px',
    borderRadius: '6px',
    border: 'none',
    cursor: 'pointer',
    fontSize: '0.9rem',
    fontWeight: '500',
    color: '#fff',
    width: '100%',
    textAlign: 'center',
    transition: 'background-color 0.3s ease-in-out',
  },
  conversationList: {
    flex: 1,
    overflowY: 'auto',
    padding: '10px',
  },
  conversationItem: {
    padding: '10px 15px',
    borderRadius: '8px',
    marginBottom: '5px',
    cursor: 'pointer',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    transition: 'background-color 0.3s ease-in-out, color 0.3s ease-in-out',
    '&:hover': {
      backgroundColor: 'rgba(0, 0, 0, 0.05)',
    },
  },
  conversationTitle: {
    fontSize: '0.95rem',
    fontWeight: '500',
    textOverflow: 'ellipsis',
    overflow: 'hidden',
    whiteSpace: 'nowrap',
    flex: 1,
    transition: 'color 0.3s ease-in-out',
  },
  deleteButton: {
    background: 'none',
    border: 'none',
    fontSize: '1.2rem',
    cursor: 'pointer',
    padding: '0 5px',
    opacity: 0.6,
    transition: 'color 0.3s ease-in-out, opacity 0.2s ease',
    '&:hover': {
      opacity: 1,
    },
  },
  chatArea: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    transition: 'width 0.3s ease-in-out',
  },
  sidebarToggle: {
    background: 'none',
    border: 'none',
    fontSize: '1.5rem',
    cursor: 'pointer',
    padding: '0 10px 0 0',
    display: 'flex',
    alignItems: 'center',
    transition: 'color 0.3s ease-in-out',
  },
  headerLeft: {
    display: 'flex',
    alignItems: 'center',
  },
  chatContainer: {
    display: 'flex',
    flexDirection: 'column',
    width: '90%',
    maxWidth: '800px',
    height: '80vh',
    borderRadius: '12px',
    overflow: 'hidden',
    boxShadow: '0 5px 15px rgba(0, 0, 0, 0.1)',
    transition: 'all 0.3s ease-in-out',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '15px 25px',
    transition: 'background-color 0.3s ease-in-out, border-bottom 0.3s ease-in-out',
  },
  headerTitle: {
    margin: 0,
    fontSize: '1.6rem',
    fontWeight: '600',
    transition: 'color 0.3s ease-in-out',
  },
  themeToggle: {
    padding: '8px 15px',
    borderRadius: '6px',
    border: 'none',
    cursor: 'pointer',
    fontSize: '0.95rem',
    fontWeight: '500',
    transition: 'background-color 0.3s ease-in-out',
  },
  chatWindow: {
    flex: 1,
    padding: '20px',
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    transition: 'background-color 0.3s ease-in-out',
  },
  inputContainer: {
    padding: '15px 20px',
    transition: 'background-color 0.3s ease-in-out, border-top 0.3s ease-in-out',
  },
  textArea: {
    width: '100%',
    height: '80px',
    padding: '12px 15px',
    fontSize: '1rem',
    borderRadius: '8px',
    resize: 'none',
    marginBottom: '12px',
    boxSizing: 'border-box',
    fontFamily: 'inherit',
    transition: 'background-color 0.3s ease-in-out, color 0.3s ease-in-out, border 0.3s ease-in-out',
    outline: 'none',
  },
  buttonGroup: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  button: {
    padding: '10px 20px',
    marginLeft: '10px',
    fontSize: '1rem',
    cursor: 'pointer',
    border: 'none',
    borderRadius: '8px',
    backgroundColor: '#007bff',
    color: '#fff',
    fontWeight: '500',
    transition: 'all 0.3s ease-in-out, background-color 0.3s ease-in-out, transform 0.2s ease',
    boxShadow: '0 2px 5px rgba(0, 0, 0, 0.1)',
    '&:hover': {
      transform: 'translateY(-2px)',
      boxShadow: '0 4px 8px rgba(0, 0, 0, 0.15)',
    },
    '&:active': {
      transform: 'translateY(1px)',
    },
  },
  resetButton: {
    backgroundColor: '#dc3545',
  },
  messageContainer: {
    display: 'flex',
    flexDirection: 'column',
    maxWidth: '75%',
    margin: '8px 0',
    wordWrap: 'break-word',
    transition: 'all 0.3s ease-in-out',
  },
  userMessageContainer: {
    alignSelf: 'flex-end',
  },
  botMessageContainer: {
    alignSelf: 'flex-start',
  },
  messageBubble: {
    padding: '12px 16px',
    borderRadius: '18px',
    boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1)',
    lineHeight: '1.4',
    transition: 'background-color 0.3s ease-in-out, color 0.3s ease-in-out, border 0.3s ease-in-out',
    position: 'relative',
    paddingBottom: '32px',
  },
  userMessage: {
    backgroundColor: '#dcf8c6',
    borderBottomRightRadius: '4px',
    transition: 'background-color 0.3s ease-in-out, color 0.3s ease-in-out',
  },
  botMessage: {
    backgroundColor: '#fff',
    border: '1px solid #e0e0e0',
    borderBottomLeftRadius: '4px',
    transition: 'background-color 0.3s ease-in-out, color 0.3s ease-in-out, border 0.3s ease-in-out',
  },
  senderName: {
    fontSize: '0.85rem',
    marginBottom: '4px',
    fontWeight: 'bold',
    transition: 'color 0.3s ease-in-out',
  },
  userSenderName: {
    textAlign: 'right',
    color: '#4a6c40',
    transition: 'color 0.3s ease-in-out',
  },
  botSenderName: {
    color: '#555',
    transition: 'color 0.3s ease-in-out',
  },
  copyButton: {
    position: 'absolute',
    bottom: '6px',
    right: '10px',
    background: 'none',
    border: 'none',
    fontSize: '0.9rem',
    cursor: 'pointer',
    padding: '4px 8px',
    borderRadius: '4px',
    opacity: 1,
    transition: 'background-color 0.2s ease-in-out',
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
    '&:hover': {
      backgroundColor: 'rgba(0, 0, 0, 0.1)',
    },
  },
};

export default styles;